# Generated by Django 4.1.5 on 2023-08-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0002_rename_reviewer_cookiestand_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiestand',
            name='location',
        ),
    ]
