# Generated by Django 4.1.5 on 2023-08-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0003_remove_cookiestand_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='location',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
